@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul 2>&1
title Generador de Proyecto Mod Forge

:: ============================
:: USER INPUT
:: ============================
echo ========================================
echo      GENERADOR DE PROYECTO MOD FORGE
echo ========================================
echo.
set /p "NombreProyecto=Nombre del proyecto (default: MiMod): "
if "%NombreProyecto%"=="" set "NombreProyecto=MiMod"
set "folderName=%NombreProyecto: =%"
set /p "ModId=Mod ID (default: nombre en minusculas): "
if "%ModId%"=="" set "ModId=%NombreProyecto%"
set "modId=%ModId: =%"

set "modId=!modId:A=a!"
set "modId=!modId:B=b!"
set "modId=!modId:C=c!"
set "modId=!modId:D=d!"
set "modId=!modId:E=e!"
set "modId=!modId:F=f!"
set "modId=!modId:G=g!"
set "modId=!modId:H=h!"
set "modId=!modId:I=i!"
set "modId=!modId:J=j!"
set "modId=!modId:K=k!"
set "modId=!modId:L=l!"
set "modId=!modId:M=m!"
set "modId=!modId:N=n!"
set "modId=!modId:O=o!"
set "modId=!modId:P=p!"
set "modId=!modId:Q=q!"
set "modId=!modId:R=r!"
set "modId=!modId:S=s!"
set "modId=!modId:T=t!"
set "modId=!modId:U=u!"
set "modId=!modId:V=v!"
set "modId=!modId:W=w!"
set "modId=!modId:X=x!"
set "modId=!modId:Y=y!"
set "modId=!modId:Z=z!"

set "pkgDefault=com.%modId%"
set /p "Paquete=Package base (default: %pkgDefault%): "
if "%Paquete%"=="" set "Paquete=%pkgDefault%"
set "pkgPath=%Paquete:.=\%"

set "ModIdClass="
set "capNext=1"
for /l %%i in (0,1,99) do (
    if "!modId:~%%i,1!"=="" goto :breakClass
    set "ch=!modId:~%%i,1!"
    if "!ch!"=="_" (
        set "capNext=1"
    ) else if !capNext!==1 (
        for %%a in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
            if /i "!ch!"=="%%a" set "ch=%%a"
        )
        set "ModIdClass=!ModIdClass!!ch!"
        set "capNext=0"
    ) else (
        set "ModIdClass=!ModIdClass!!ch!"
    )
)
:breakClass

set "DisplayName=%NombreProyecto%"
set /p "Author=Autor: "
if "%Author%"=="" set "Author=Autor"
set "VersionMinecraft=1.20.1"
set "VersionForge=47.3.0"

echo.
echo Resumen:
echo   Proyecto:     %folderName%
echo   Mod ID:       %modId%
echo   Package:      %Paquete%
echo   Display Name: %DisplayName%
echo   Clase princ:  %ModIdClass%.java
echo   Autor:        %Author%
echo   Forge:        %VersionMinecraft%-%VersionForge%
echo.
set /p "confirm=Crear proyecto? (S/n): "
if /i "%confirm%"=="n" echo Cancelado.& exit /b
set "basePath=%cd%\%folderName%"

echo.
echo Creando estructura de carpetas...
mkdir "%basePath%" 2>nul
mkdir "%basePath%\gradle\wrapper" 2>nul
mkdir "%basePath%\src\main\java\%pkgPath%\client" 2>nul
mkdir "%basePath%\src\main\resources\META-INF" 2>nul
mkdir "%basePath%\src\main\resources\assets\%modId%\lang" 2>nul
mkdir "%basePath%\src\main\resources\assets\%modId%\sounds" 2>nul
mkdir "%basePath%\src\main\resources\assets\%modId%\textures\entity" 2>nul
mkdir "%basePath%\src\generated\resources" 2>nul

:: ============================
:: GENERATE POWERSHELL SCRIPT
:: ============================
echo Creando archivos del proyecto...

set "PF=%temp%\gen_mod_project.ps1"
echo. > "%PF%"

echo $modId='%modId%'>> "%PF%"
echo $ModIdClass='%ModIdClass%'>> "%PF%"
echo $Paquete='%Paquete%'>> "%PF%"
echo $pkgPath='%pkgPath%'>> "%PF%"
echo $DisplayName='%DisplayName%'>> "%PF%"
echo $Author='%Author%'>> "%PF%"
echo $VersionMinecraft='%VersionMinecraft%'>> "%PF%"
echo $VersionForge='%VersionForge%'>> "%PF%"
echo $basePath='%basePath%'>> "%PF%"
echo $srcDir='%~dp0'>> "%PF%"
echo function w($f,$c){[System.IO.File]::WriteAllText((Join-Path $basePath $f),$c)}>> "%PF%"
echo.>> "%PF%"

:: gradle-wrapper.properties
echo w 'gradle\wrapper\gradle-wrapper.properties' @">> "%PF%"
echo distributionBase=GRADLE_USER_HOME>> "%PF%"
echo distributionPath=wrapper/dists>> "%PF%"
echo distributionUrl=https://services.gradle.org/distributions/gradle-8.1.1-bin.zip>> "%PF%"
echo networkTimeout=10000>> "%PF%"
echo validateDistributionUrl=true>> "%PF%"
echo zipStoreBase=GRADLE_USER_HOME>> "%PF%"
echo zipStorePath=wrapper/dists>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: settings.gradle
echo w 'settings.gradle' @">> "%PF%"
echo pluginManagement {>> "%PF%"
echo     repositories {>> "%PF%"
echo         gradlePluginPortal()>> "%PF%"
echo         maven { url = 'https://maven.minecraftforge.net' }>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo plugins {>> "%PF%"
echo     id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'>> "%PF%"
echo }>> "%PF%"
echo rootProject.name = '%modId%'>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: gradle.properties
echo w 'gradle.properties' @">> "%PF%"
echo org.gradle.jvmargs=-Xmx3G>> "%PF%"
echo org.gradle.daemon=false>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: build.gradle
echo w 'build.gradle' @">> "%PF%"
echo buildscript {>> "%PF%"
echo     repositories {>> "%PF%"
echo         maven { url = 'https://maven.minecraftforge.net' }>> "%PF%"
echo         mavenCentral()>> "%PF%"
echo     }>> "%PF%"
echo     dependencies {>> "%PF%"
echo         classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.0.+', changing: true>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo plugins { id 'eclipse'; id 'idea' }>> "%PF%"
echo apply plugin: 'net.minecraftforge.gradle'>> "%PF%"
echo group = '%Paquete%'>> "%PF%"
echo version = '1.0.0'>> "%PF%"
echo java {>> "%PF%"
echo     archivesBaseName = '%modId%'>> "%PF%"
echo     toolchain.languageVersion = JavaLanguageVersion.of(17)>> "%PF%"
echo }>> "%PF%"
echo minecraft {>> "%PF%"
echo     mappings channel: 'official', version: '%VersionMinecraft%'>> "%PF%"
echo     runs {>> "%PF%"
echo         client {>> "%PF%"
echo             workingDirectory project.file('run')>> "%PF%"
echo             property 'forge.logging.markers', 'REGISTRIES'>> "%PF%"
echo             property 'forge.logging.console.level', 'debug'>> "%PF%"
echo             property 'forge.enabledGameTestNamespaces', '%modId%'>> "%PF%"
echo             mods { %modId% { source sourceSets.main } }>> "%PF%"
echo         }>> "%PF%"
echo         server {>> "%PF%"
echo             workingDirectory project.file('run')>> "%PF%"
echo             property 'forge.logging.markers', 'REGISTRIES'>> "%PF%"
echo             property 'forge.logging.console.level', 'debug'>> "%PF%"
echo             property 'forge.enabledGameTestNamespaces', '%modId%'>> "%PF%"
echo             mods { %modId% { source sourceSets.main } }>> "%PF%"
echo         }>> "%PF%"
echo         gameTestServer {>> "%PF%"
echo             workingDirectory project.file('run')>> "%PF%"
echo             property 'forge.logging.markers', 'REGISTRIES'>> "%PF%"
echo             property 'forge.logging.console.level', 'debug'>> "%PF%"
echo             property 'forge.enabledGameTestNamespaces', '%modId%'>> "%PF%"
echo             mods { %modId% { source sourceSets.main } }>> "%PF%"
echo         }>> "%PF%"
echo         data {>> "%PF%"
echo             workingDirectory project.file('run')>> "%PF%"
echo             property 'forge.logging.markers', 'REGISTRIES'>> "%PF%"
echo             property 'forge.logging.console.level', 'debug'>> "%PF%"
echo             args '--mod', '%modId%', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')>> "%PF%"
echo             mods { %modId% { source sourceSets.main } }>> "%PF%"
echo         }>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo sourceSets.main.resources { srcDir 'src/generated/resources' }>> "%PF%"
echo repositories {}>> "%PF%"
echo dependencies {>> "%PF%"
echo     minecraft 'net.minecraftforge:forge:%VersionMinecraft%-%VersionForge%'>> "%PF%"
echo }>> "%PF%"
echo jar {>> "%PF%"
echo     manifest {>> "%PF%"
echo         attributes([]>> "%PF%"
echo                 'Specification-Title': '%DisplayName%',>> "%PF%"
echo                 'Specification-Vendor': '%Author%',>> "%PF%"
echo                 'Specification-Version': '1',>> "%PF%"
echo                 'Implementation-Title': project.name,>> "%PF%"
echo                 'Implementation-Version': project.jar.archiveVersion,>> "%PF%"
echo                 'Implementation-Vendor': '%Author%',>> "%PF%"
echo                 'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")>> "%PF%"
echo         ])>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo jar.finalizedBy('reobfJar')>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: mods.toml
echo w 'src\main\resources\META-INF\mods.toml' @">> "%PF%"
echo modLoader="javafml">> "%PF%"
echo loaderVersion="[47,)">> "%PF%"
echo license="All rights reserved">> "%PF%"
echo.>> "%PF%"
echo [[mods]]>> "%PF%"
echo modId="%modId%">> "%PF%"
echo version="1.0.0">> "%PF%"
echo displayName="%DisplayName%">> "%PF%"
echo credits="Creado por %Author%">> "%PF%"
echo authors="%Author%">> "%PF%"
echo description='''>> "%PF%"
echo %DisplayName% - Un mod creado con el generador de proyectos!>> "%PF%"
echo '''>> "%PF%"
echo.>> "%PF%"
echo [[dependencies.%modId%]]>> "%PF%"
echo modId="forge">> "%PF%"
echo mandatory=true>> "%PF%"
echo versionRange="[%VersionForge%,)">> "%PF%"
echo ordering="NONE">> "%PF%"
echo side="BOTH">> "%PF%"
echo.>> "%PF%"
echo [[dependencies.%modId%]]>> "%PF%"
echo modId="minecraft">> "%PF%"
echo mandatory=true>> "%PF%"
echo versionRange="[%VersionMinecraft%,1.21)">> "%PF%"
echo ordering="NONE">> "%PF%"
echo side="BOTH">> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: pack.mcmeta
echo w 'src\main\resources\pack.mcmeta' @">> "%PF%"
echo {>> "%PF%"
echo     "pack": {>> "%PF%"
echo         "description": "%modId% resources",>> "%PF%"
echo         "pack_format": 15>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: ModEntities.java
echo $jDir="src/main/java/%pkgPath%">> "%PF%"
echo w "$jDir/ModEntities.java" @">> "%PF%"
echo package %Paquete%;>> "%PF%"
echo.>> "%PF%"
echo import net.minecraft.resources.ResourceLocation;>> "%PF%"
echo import net.minecraft.world.entity.EntityType;>> "%PF%"
echo import net.minecraft.world.entity.MobCategory;>> "%PF%"
echo import net.minecraftforge.eventbus.api.IEventBus;>> "%PF%"
echo import net.minecraftforge.registries.DeferredRegister;>> "%PF%"
echo import net.minecraftforge.registries.ForgeRegistries;>> "%PF%"
echo import net.minecraftforge.registries.RegistryObject;>> "%PF%"
echo.>> "%PF%"
echo public class ModEntities {>> "%PF%"
echo     public static final DeferredRegister<EntityType<?>> ENTITIES =>> "%PF%"
echo             DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, %ModIdClass%.MODID);>> "%PF%"
echo     public static void register(IEventBus eventBus) { ENTITIES.register(eventBus); }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: ModSounds.java
echo w "$jDir/ModSounds.java" @">> "%PF%"
echo package %Paquete%;>> "%PF%"
echo.>> "%PF%"
echo import net.minecraft.resources.ResourceLocation;>> "%PF%"
echo import net.minecraft.sounds.SoundEvent;>> "%PF%"
echo import net.minecraftforge.eventbus.api.IEventBus;>> "%PF%"
echo import net.minecraftforge.registries.DeferredRegister;>> "%PF%"
echo import net.minecraftforge.registries.ForgeRegistries;>> "%PF%"
echo import net.minecraftforge.registries.RegistryObject;>> "%PF%"
echo.>> "%PF%"
echo public class ModSounds {>> "%PF%"
echo     public static final DeferredRegister<SoundEvent> SOUNDS =>> "%PF%"
echo             DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, %ModIdClass%.MODID);>> "%PF%"
echo     public static void register(IEventBus bus) { SOUNDS.register(bus); }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: EventQueueManager.java
echo w "$jDir/EventQueueManager.java" @">> "%PF%"
echo package %Paquete%;>> "%PF%"
echo.>> "%PF%"
echo import java.util.HashMap;>> "%PF%"
echo import java.util.LinkedList;>> "%PF%"
echo import java.util.Map;>> "%PF%"
echo import java.util.Queue;>> "%PF%"
echo import java.util.UUID;>> "%PF%"
echo.>> "%PF%"
echo public class EventQueueManager {>> "%PF%"
echo     private final Map<UUID, Queue<Runnable>> eventQueues = new HashMap<>();>> "%PF%"
echo     private final Map<UUID, Runnable> activeEvents = new HashMap<>();>> "%PF%"
echo     public void queueOrExecute(UUID targetId, Runnable event) {>> "%PF%"
echo         if (activeEvents.containsKey(targetId)) {>> "%PF%"
echo             eventQueues.computeIfAbsent(targetId, k -> new LinkedList<>()).add(event);>> "%PF%"
echo         } else {>> "%PF%"
echo             activeEvents.put(targetId, event);>> "%PF%"
echo             event.run();>> "%PF%"
echo         }>> "%PF%"
echo     }>> "%PF%"
echo     public void onEventCompleted(UUID targetId) {>> "%PF%"
echo         activeEvents.remove(targetId);>> "%PF%"
echo         Queue<Runnable> queue = eventQueues.get(targetId);>> "%PF%"
echo         if (queue != null && !queue.isEmpty()) {>> "%PF%"
echo             Runnable next = queue.poll();>> "%PF%"
echo             activeEvents.put(targetId, next);>> "%PF%"
echo             next.run();>> "%PF%"
echo         }>> "%PF%"
echo     }>> "%PF%"
echo     public boolean hasActiveEvent(UUID targetId) { return activeEvents.containsKey(targetId); }>> "%PF%"
echo     public void clearAll() { activeEvents.clear(); eventQueues.clear(); }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: Main mod class
echo w "$jDir/%ModIdClass%.java" @">> "%PF%"
echo package %Paquete%;>> "%PF%"
echo.>> "%PF%"
echo import com.mojang.brigadier.CommandDispatcher;>> "%PF%"
echo import com.mojang.logging.LogUtils;>> "%PF%"
echo import net.minecraft.commands.CommandSourceStack;>> "%PF%"
echo import net.minecraft.commands.Commands;>> "%PF%"
echo import net.minecraft.server.level.ServerPlayer;>> "%PF%"
echo import net.minecraft.world.entity.Entity;>> "%PF%"
echo import net.minecraftforge.common.MinecraftForge;>> "%PF%"
echo import net.minecraftforge.event.RegisterCommandsEvent;>> "%PF%"
echo import net.minecraftforge.event.TickEvent;>> "%PF%"
echo import net.minecraftforge.event.entity.EntityLeaveLevelEvent;>> "%PF%"
echo import net.minecraftforge.event.server.ServerStoppingEvent;>> "%PF%"
echo import net.minecraftforge.eventbus.api.IEventBus;>> "%PF%"
echo import net.minecraftforge.eventbus.api.SubscribeEvent;>> "%PF%"
echo import net.minecraftforge.fml.common.Mod;>> "%PF%"
echo import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;>> "%PF%"
echo import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;>> "%PF%"
echo import org.slf4j.Logger;>> "%PF%"
echo import java.util.HashMap;>> "%PF%"
echo import java.util.Map;>> "%PF%"
echo import java.util.UUID;>> "%PF%"
echo.>> "%PF%"
echo @Mod(%ModIdClass%.MODID)>> "%PF%"
echo public class %ModIdClass% {>> "%PF%"
echo     public static final String MODID = "%modId%";>> "%PF%"
echo     public static final EventQueueManager EVENT_QUEUE = new EventQueueManager();>> "%PF%"
echo     private static final Logger LOGGER = LogUtils.getLogger();>> "%PF%"
echo     private final Map<Integer, UUID> entityToTarget = new HashMap<>();>> "%PF%"
echo     public %ModIdClass%() {>> "%PF%"
echo         IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();>> "%PF%"
echo         ModEntities.register(modEventBus);>> "%PF%"
echo         ModSounds.SOUNDS.register(modEventBus);>> "%PF%"
echo         modEventBus.addListener(this::commonSetup);>> "%PF%"
echo         MinecraftForge.EVENT_BUS.addListener(this::onRegisterCommands);>> "%PF%"
echo         MinecraftForge.EVENT_BUS.addListener(this::onEntityLeave);>> "%PF%"
echo         MinecraftForge.EVENT_BUS.addListener(this::onServerTick);>> "%PF%"
echo         MinecraftForge.EVENT_BUS.addListener(this::onServerStopping);>> "%PF%"
echo     }>> "%PF%"
echo     private void commonSetup(FMLCommonSetupEvent e) { LOGGER.info("%DisplayName% cargado!"); }>> "%PF%"
echo     private void onServerStopping(ServerStoppingEvent e) { EVENT_QUEUE.clearAll(); entityToTarget.clear(); }>> "%PF%"
echo     private void onEntityLeave(EntityLeaveLevelEvent e) {>> "%PF%"
echo         UUID t = entityToTarget.remove(e.getEntity().getId());>> "%PF%"
echo         if (t != null) EVENT_QUEUE.onEventCompleted(t);>> "%PF%"
echo     }>> "%PF%"
echo     private void onServerTick(TickEvent.ServerTickEvent e) { if (e.phase != TickEvent.Phase.END) return; }>> "%PF%"
echo     protected void trackEntity(Entity entity, UUID targetId) { entityToTarget.put(entity.getId(), targetId); }>> "%PF%"
echo     private void onRegisterCommands(RegisterCommandsEvent e) {>> "%PF%"
echo         CommandDispatcher<CommandSourceStack> d = e.getDispatcher();>> "%PF%"
echo         LOGGER.info("Comandos registrados");>> "%PF%"
echo     }>> "%PF%"
echo     @Mod.EventBusSubscriber(modid = MODID, bus = Mod.EventBusSubscriber.Bus.MOD, value = net.minecraftforge.api.distmarker.Dist.CLIENT)>> "%PF%"
echo     public static class ClientModEvents {>> "%PF%"
echo         @SubscribeEvent>> "%PF%"
echo         public static void onRegisterRenderers(net.minecraftforge.client.event.EntityRenderersEvent.RegisterRenderers e) {}>> "%PF%"
echo         @SubscribeEvent>> "%PF%"
echo         public static void onRegisterLayerDefinitions(net.minecraftforge.client.event.EntityRenderersEvent.RegisterLayerDefinitions e) {}>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: en_us.json
echo w "src\main\resources\assets\%modId%\lang\en_us.json" @">> "%PF%"
echo {>> "%PF%"
echo     "item.%modId%.placeholder": "Placeholder">> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: sounds.json
echo w "src\main\resources\assets\%modId%\sounds.json" @">> "%PF%"
echo {>> "%PF%"
echo     "mi_sonido": {>> "%PF%"
echo         "subtitle": "Mi sonido",>> "%PF%"
echo         "sounds": [>> "%PF%"
echo             "%modId%:entity/mi_sonido">> "%PF%"
echo         ]>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo "@>> "%PF%"
echo.>> "%PF%"

:: README texture placeholder
echo [System.IO.File]::WriteAllText("$basePath/src/main/resources/assets/$modId/textures/entity/README.txt", "Place a 64x64 PNG texture here.")>> "%PF%"
echo.>> "%PF%"

:: gradlew.bat
echo if (Test-Path (Join-Path $srcDir 'gradlew.bat')) { Copy-Item (Join-Path $srcDir 'gradlew.bat') (Join-Path $basePath 'gradlew.bat'); Write-Host '  gradlew.bat copied' }>> "%PF%"
echo.>> "%PF%"

:: ===================== DOCS =====================
echo w 'DAMAGE_GUIDE.md' @'>> "%PF%"
echo # Como implementar dano por tick sin invulnerabilidad>> "%PF%"
echo.>> "%PF%"
echo ## Requisitos>> "%PF%"
echo - Forge 1.20.1 (Mojang mappings)>> "%PF%"
echo - Una entidad que detecta un "impacto" o "grapple">> "%PF%"
echo.>> "%PF%"
echo ## Paso 1: En tu entidad>> "%PF%"
echo.>> "%PF%"
echo Cuando la entidad impacta al jugador (ej: `dist <= IMPACT_DIST`), anade UNA SOLA linea:>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo if (target instanceof ServerPlayer sp) TuMod.onGrappleStart(sp);>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ## Paso 2: En la clase de tu mod>> "%PF%"
echo.>> "%PF%"
echo ### 2a. Anade un mapa estatico>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo private static final Map<UUID, Integer> GRAPPLE_TIMERS = new HashMap<>();>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ### 2b. Metodo estatico que activa el dano>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo public static void onGrappleStart(ServerPlayer target) {>> "%PF%"
echo     GRAPPLE_TIMERS.put(target.getUUID(), 300); // 300 ticks = 15 segundos>> "%PF%"
echo }>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ### 2c. En el ServerTickEvent>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo @SubscribeEvent>> "%PF%"
echo public void onServerTick(TickEvent.ServerTickEvent event) {>> "%PF%"
echo     if (event.phase != TickEvent.Phase.END) return;>> "%PF%"
echo     MinecraftServer server = ServerLifecycleHooks.getCurrentServer();>> "%PF%"
echo     if (server == null) return;>> "%PF%"
echo     for (UUID uuid : new ArrayList<>(GRAPPLE_TIMERS.keySet())) {>> "%PF%"
echo         int ticks = GRAPPLE_TIMERS.get(uuid);>> "%PF%"
echo         if (--ticks <= 0) { GRAPPLE_TIMERS.remove(uuid); continue; }>> "%PF%"
echo         GRAPPLE_TIMERS.put(uuid, ticks);>> "%PF%"
echo         ServerPlayer target = (ServerPlayer) server.getPlayerList().getPlayer(uuid);>> "%PF%"
echo         if (target == null || !target.isAlive() || target.isCreative()) {>> "%PF%"
echo             GRAPPLE_TIMERS.remove(uuid);>> "%PF%"
echo             continue;>> "%PF%"
echo         }>> "%PF%"
echo         target.hurt(server.overworld().damageSources().outOfBorder(), 75.0f);>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ### 2d. Handler que resetea invulnerabilidad>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo private static java.lang.reflect.Field INVULN_FIELD;>> "%PF%"
echo try {>> "%PF%"
echo     INVULN_FIELD = LivingEntity.class.getDeclaredField("invulnerableTime");>> "%PF%"
echo     INVULN_FIELD.setAccessible(true);>> "%PF%"
echo } catch (Exception e) {>> "%PF%"
echo     try {>> "%PF%"
echo         INVULN_FIELD = LivingEntity.class.getDeclaredField("noDamageTicks");>> "%PF%"
echo         INVULN_FIELD.setAccessible(true);>> "%PF%"
echo     } catch (Exception ignored) {}>> "%PF%"
echo }>> "%PF%"
echo @SubscribeEvent>> "%PF%"
echo public void onLivingDamage(LivingDamageEvent event) {>> "%PF%"
echo     if (INVULN_FIELD != null && event.getSource().is(DamageTypeTags.BYPASSES_COOLDOWN)) {>> "%PF%"
echo         try { INVULN_FIELD.setInt(event.getEntity(), 0); } catch (Exception ignored) {}>> "%PF%"
echo     }>> "%PF%"
echo }>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ## Explicacion>> "%PF%"
echo.>> "%PF%"
echo | Componente | Por que |>> "%PF%"
echo |---|---|>> "%PF%"
echo | `Map<UUID, Integer>` | Timer por jugador, sin escanear entidades |>> "%PF%"
echo | `outOfBorder()` | Dano que bypasea cooldown por tag vanilla |>> "%PF%"
echo | `LivingDamageEvent` | Resetea el contador que `hurt()` pone a 10 |>> "%PF%"
echo | Llamada desde la entidad | El dano empieza EXACTAMENTE cuando impacta |>> "%PF%"
echo.>> "%PF%"
echo ## Lo que EVITAMOS>> "%PF%"
echo - Escanear entidades con `getAll()` (falla en Mohist)>> "%PF%"
echo - Trackear entidades por ID numerico (no confiable)>> "%PF%"
echo - Eventos `EntityJoinLevelEvent`/`EntityLeaveLevelEvent`>> "%PF%"
echo - Bucles de dano sin control (usa timer con limite de ticks)>> "%PF%"
echo '@>> "%PF%"
echo.>> "%PF%"

echo w 'COMPILAR_MOD.md' @'>> "%PF%"
echo # Como compilar el mod a JAR>> "%PF%"
echo.>> "%PF%"
echo Instrucciones para compilar un mod de Forge 1.20.1 usando Gradle.>> "%PF%"
echo.>> "%PF%"
echo ## Requisitos>> "%PF%"
echo.>> "%PF%"
echo | Requisito | Version |>> "%PF%"
echo |-----------|---------|>> "%PF%"
echo | Java JDK | 17 o superior |>> "%PF%"
echo | Gradle | 8.1.1 (incluido en gradlew.bat) |>> "%PF%"
echo | Git | Opcional |>> "%PF%"
echo.>> "%PF%"
echo Verifica Java: `java -version`>> "%PF%"
echo Debe mostrar `openjdk version "17.0.x"` o superior.>> "%PF%"
echo.>> "%PF%"
echo ## Compilar el JAR>> "%PF%"
echo.>> "%PF%"
echo 1. Abre una terminal en la carpeta del proyecto>> "%PF%"
echo 2. Ejecuta `.\gradlew.bat` (descarga Gradle y Forge, primera vez tarda)>> "%PF%"
echo 3. Ejecuta `.\gradlew.bat build`>> "%PF%"
echo 4. El JAR esta en `build/libs/<modid>-1.0.0.jar`>> "%PF%"
echo.>> "%PF%"
echo ## Instalar el mod>> "%PF%"
echo.>> "%PF%"
echo 1. Copia el `.jar` a la carpeta `mods/` de tu Minecraft>> "%PF%"
echo 2. Forge 1.20.1 debe estar instalado en el perfil>> "%PF%"
echo 3. Inicia Minecraft>> "%PF%"
echo.>> "%PF%"
echo ## Comandos utiles>> "%PF%"
echo.>> "%PF%"
echo | Comando | Que hace |>> "%PF%"
echo |---------|----------|>> "%PF%"
echo | `.\gradlew.bat build` | Compila el JAR |>> "%PF%"
echo | `.\gradlew.bat clean` | Borra build/ |>> "%PF%"
echo | `.\gradlew.bat runClient` | Ejecuta Minecraft |>> "%PF%"
echo | `.\gradlew.bat runServer` | Ejecuta servidor |>> "%PF%"
echo | `.\gradlew.bat --stop` | Detiene el daemon de Gradle |>> "%PF%"
echo.>> "%PF%"
echo ## Solucion de problemas>> "%PF%"
echo.>> "%PF%"
echo - **Java not found**: Configura JAVA_HOME en tus variables de entorno>> "%PF%"
echo - **Out of memory**: Edita `gradle.properties`, aumenta -Xmx>> "%PF%"
echo - **BUILD FAILED**: Revisa errores de compilacion en la terminal>> "%PF%"
echo - **JAR no funciona**: Verifica mods.toml, @Mod, MODID>> "%PF%"
echo '@>> "%PF%"
echo.>> "%PF%"

echo w 'COMO_AGREGAR_SONIDOS.md' @'>> "%PF%"
echo # Como agregar sonidos al mod>> "%PF%"
echo.>> "%PF%"
echo Basado en el sistema de sonidos del mod Rasengan (Forge 1.20.1, Mojang mappings).>> "%PF%"
echo.>> "%PF%"
echo ## Archivos a tocar (4)>> "%PF%"
echo.>> "%PF%"
echo | Archivo | Proposito |>> "%PF%"
echo |---------|-----------|>> "%PF%"
echo | `ModSounds.java` | Registrar el SoundEvent |>> "%PF%"
echo | `sounds.json` | Mapear ID del sonido al .ogg |>> "%PF%"
echo | `.ogg` file | El audio en `assets/<modid>/sounds/` |>> "%PF%"
echo | Tu codigo | Reproducir sonido con `playSound()` |>> "%PF%"
echo.>> "%PF%"
echo ## 1. Prepara tu audio (.ogg)>> "%PF%"
echo.>> "%PF%"
echo Usa Audacity o FFmpeg para convertir a OGG Vorbis.>> "%PF%"
echo Guarda en: `src/main/resources/assets/<modid>/sounds/entity/<nombre>.ogg`>> "%PF%"
echo.>> "%PF%"
echo ## 2. Registra el SoundEvent en ModSounds.java>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo public static final RegistryObject<SoundEvent> MI_SONIDO =>> "%PF%"
echo         SOUNDS.register("mi_sonido",>> "%PF%"
echo             () -> SoundEvent.createVariableRangeEvent(>> "%PF%"
echo                 new ResourceLocation(ModID, "mi_sonido")));>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ## 3. Crea sounds.json>> "%PF%"
echo.>> "%PF%"
echo Ubicacion: `src/main/resources/assets/<modid>/sounds.json`>> "%PF%"
echo.>> "%PF%"
echo ```json>> "%PF%"
echo { "mi_sonido": {>> "%PF%"
echo     "subtitle": "Mi sonido",>> "%PF%"
echo     "sounds": [ "<modid>:entity/mi_sonido" ]>> "%PF%"
echo } }>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo ## 4. Reproduce el sonido>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo level().playSound(null, x, y, z,>> "%PF%"
echo     ModSounds.MI_SONIDO.get(), SoundSource.PLAYERS, 3.0f, 1.0f);>> "%PF%"
echo ```>> "%PF%"
echo.>> "%PF%"
echo Parametros: `null`=todos, `x,y,z`=posicion, `SoundEvent`, `SoundSource`, `volume`, `pitch`>> "%PF%"
echo '@>> "%PF%"
echo.>> "%PF%"

echo w 'COMO_CREAR_NUEVA_ENTIDAD.md' @'>> "%PF%"
echo # Como crear una nueva entidad (basada en Stickman)>> "%PF%"
echo.>> "%PF%"
echo Guia paso a paso para crear un personaje similar al Stickman (Naruto).>> "%PF%"
echo.>> "%PF%"
echo ## Archivos a crear (6)>> "%PF%"
echo.>> "%PF%"
echo | Archivo | Proposito |>> "%PF%"
echo |---------|-----------|>> "%PF%"
echo | `MiPersonajeEntity.java` | Logica de la entidad |>> "%PF%"
echo | `client/MiPersonajeModel.java` | Modelo 3D humanoide |>> "%PF%"
echo | `client/MiPersonajeRenderer.java` | Render con skin |>> "%PF%"
echo | `textures/entity/mi_personaje.png` | Skin PNG 64x64 |>> "%PF%"
echo | Modificar `ModEntities.java` | Registrar la entidad |>> "%PF%"
echo | Modificar clase principal | Registrar render + comando |>> "%PF%"
echo.>> "%PF%"
echo ## 1. Crea la textura (PNG 64x64)>> "%PF%"
echo.>> "%PF%"
echo Usa el layout UV vanilla: Head(0,0), Body(16,16), Arms(40,16), Legs(0,16)>> "%PF%"
echo Guarda en `assets/<modid>/textures/entity/mi_personaje.png`>> "%PF%"
echo.>> "%PF%"
echo ## 2. Crea el modelo (MiPersonajeModel.java)>> "%PF%"
echo.>> "%PF%"
echo Extiende EntityModel. Usa ModelLayerLocation. Define partes: head, body, rightArm, leftArm, rightLeg, leftLeg.>> "%PF%"
echo En setupAnim() controla la animacion segun getAnimState():>> "%PF%"
echo - 0: quieto>> "%PF%"
echo - 1: cargando (brazo derecho levantado)>> "%PF%"
echo - 2: lanzo (cuerpo inclinado)>> "%PF%"
echo.>> "%PF%"
echo ## 3. Crea el Renderer (MiPersonajeRenderer.java)>> "%PF%"
echo.>> "%PF%"
echo Extiende EntityRenderer. En render(): escala -1x-1x1, rota hacia el jugador, llama model.renderToBuffer().>> "%PF%"
echo Para skins multiples, usa un array de ResourceLocation y un skinIndex.>> "%PF%"
echo.>> "%PF%"
echo ## 4. Crea la entidad (MiPersonajeEntity.java)>> "%PF%"
echo.>> "%PF%"
echo Extiende Entity. Usa SynchedEntityData para ANIM_STATE y RASENGAN_ID.>> "%PF%"
echo En tick():>> "%PF%"
echo - Fase carga (100 ticks): animState=1, genera Rasengan en la mano>> "%PF%"
echo - Fase lanzamiento: animState=2, da velocidad al Rasengan hacia el target>> "%PF%"
echo - Fase sigue: se mueve con el Rasengan hasta que desaparezca>> "%PF%"
echo.>> "%PF%"
echo ## 5. Registra en ModEntities.java>> "%PF%"
echo.>> "%PF%"
echo Agrega: `ENTITIES.register("mi_personaje", () -> EntityType.Builder.of(...))`>> "%PF%"
echo.>> "%PF%"
echo ## 6. Registra el renderer en la clase principal>> "%PF%"
echo.>> "%PF%"
echo En ClientModEvents: registerEntityRenderer + registerLayerDefinition>> "%PF%"
echo.>> "%PF%"
echo ## 7. Crea un comando>> "%PF%"
echo.>> "%PF%"
echo Usa Commands.literal("mipersonaje") con EVENT_QUEUE.queueOrExecute()>> "%PF%"
echo.>> "%PF%"
echo ```java>> "%PF%"
echo // Ejemplo de comando>> "%PF%"
echo dispatcher.register(Commands.literal("mipersonaje")>> "%PF%"
echo     .executes(ctx -> {>> "%PF%"
echo         ServerPlayer sender = (ServerPlayer) ctx.getSource().getEntity();>> "%PF%"
echo         MiPersonajeEntity e = ModEntities.MI_PERSONAJE.get().create(sender.serverLevel());>> "%PF%"
echo         e.setPos(sender.position()); e.setTarget(sender);>> "%PF%"
echo         sender.serverLevel().addFreshEntity(e);>> "%PF%"
echo         return 1;>> "%PF%"
echo     }));>> "%PF%"
echo ```>> "%PF%"
echo '@>> "%PF%"

:: ============================
:: EXECUTE POWERSHELL SCRIPT
:: ============================
powershell -NoProfile -ExecutionPolicy Bypass -File "%PF%"
del "%PF%" 2>nul

:: ============================
:: DONE
:: ============================
echo.
echo ========================================
echo   PROYECTO CREADO CON EXITO!
echo ========================================
echo.
echo   Ruta: %basePath%
echo.
echo   Pasos siguientes:
echo   1. cd %folderName%
echo   2. .\gradlew.bat
echo   3. Abre el proyecto en tu IDE
echo   4. .\gradlew.bat build (para compilar el JAR)
echo.
echo   Clase principal: src\main\java\%pkgPath%\%ModIdClass%.java
echo ========================================
pause
